apiVersion: v1
kind: Pod
metadata: 
  name: front-end
  labels:
    app: front-end
    project: roboshop
    env: dev
    version: "1.0"
spec:   
  containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80