apiVersion: v1
kind: Pod
metadata: 
  name: learning_resource
spec:
  containers:
  - name: learning_resource
    image: nginx
    resources:
      requests:
        memory: "68Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "120m"