apiVersion: v1
kind: Pod
metadata:
  name: my-pod-service-use
  labels:
    project: roboshop
    component: frontend
    environement: dev
spec:
  containers:
  - name: my-container-nginx
    image: nginx