apiVersion: v1
kind: Service
metadata:
  name: service-node-port
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    environement: dev
    purpose: node-port
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80