apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    environement: dev
    purpose: load-balancer
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80
      nodePort: 30007