apiVersion: v1                      # ✅ Correct capitalization
kind: ConfigMap                     # Stores configuration data
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |                         # Multiline config file content
    [mysqld]
    innodb_redo_log_capacity = 2G

---
apiVersion: apps/v1
kind: Deployment                    # Creates MySQL Pod(s)
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: database

spec:
  replicas: 1                       # Run 1 MySQL pod

  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: database

  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: database

    spec:
      containers:
        - name: mysql
          image: tejahere/mysql:v1
          imagePullPolicy: Always   # Always pull image from Docker Hub

          readinessProbe:           # Pod ready check
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:            # Pod health check
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 5

          ports:
            - containerPort: 3306   # MySQL default port

          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf

      volumes:
        - name: mysql-config
          configMap:
            name: mysql             # Mount ConfigMap into pod

---
apiVersion: v1
kind: Service                       # Exposes MySQL inside cluster
metadata:
  name: mysql
  namespace: roboshop

spec:
  selector:
    project: roboshop
    component: mysql
    tier: database

  ports:
    - protocol: TCP
      port: 3306        # Service port
      targetPort: 3306  # Container port
