apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: tejahere/mysql:v1
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mysql
    tier: database
  ports:
    - protocol: TCP
      port: 3306  # service port
      targetPort: 3306 # container port